#!/usr/bin/env bash
# lint

set -euo pipefail

rustup update stable && rustup default stable
tools/ci/check_rust_deps template-check-derive

if ! command -v cargo-machete >/dev/null 2>&1; then
    cargo install cargo-machete
fi
cargo machete

cargo fmt --all -- --check
cargo generate-lockfile --locked
cargo clippy --locked -- --deny warnings
cargo verify-project --locked
cargo doc --no-deps
